//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket.Entity
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonConfigCacheBO", Namespace="http://schemas.datacontract.org/2004/07/Ticket.Entity", IsReference=true)]
    public partial class CommonConfigCacheBO : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AgentIDField;
        
        private decimal AgentRefundFeesField;
        
        private int Begin_Working_TimeField;
        
        private int CancelTempOrder_TimeOutMinutesField;
        
        private string CtripContactEmailField;
        
        private string CustomerIDField;
        
        private string DirectOrderCityField;
        
        private int End_Working_TimeField;
        
        private string EngineTypeField;
        
        private string NotifyCtripTicketingFailureEmailField;
        
        private string PCCCodeField;
        
        private int PreBookingDays_OfflineField;
        
        private int PreBookingDays_OnlineField;
        
        private int PreTicketDays_OfflineField;
        
        private int PreTicketDays_OnlineField;
        
        private int PreTicketDays_PBSField;
        
        private decimal PriceChange_MaxAmount_OnlineField;
        
        private string PromotionField;
        
        private string SourceAppIDField;
        
        private string SourceURLField;
        
        private string TicketorField;
        
        private decimal WingonRerouteFeesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AgentRefundFees
        {
            get
            {
                return this.AgentRefundFeesField;
            }
            set
            {
                this.AgentRefundFeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Begin_Working_Time
        {
            get
            {
                return this.Begin_Working_TimeField;
            }
            set
            {
                this.Begin_Working_TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CancelTempOrder_TimeOutMinutes
        {
            get
            {
                return this.CancelTempOrder_TimeOutMinutesField;
            }
            set
            {
                this.CancelTempOrder_TimeOutMinutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CtripContactEmail
        {
            get
            {
                return this.CtripContactEmailField;
            }
            set
            {
                this.CtripContactEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DirectOrderCity
        {
            get
            {
                return this.DirectOrderCityField;
            }
            set
            {
                this.DirectOrderCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int End_Working_Time
        {
            get
            {
                return this.End_Working_TimeField;
            }
            set
            {
                this.End_Working_TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngineType
        {
            get
            {
                return this.EngineTypeField;
            }
            set
            {
                this.EngineTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotifyCtripTicketingFailureEmail
        {
            get
            {
                return this.NotifyCtripTicketingFailureEmailField;
            }
            set
            {
                this.NotifyCtripTicketingFailureEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PCCCode
        {
            get
            {
                return this.PCCCodeField;
            }
            set
            {
                this.PCCCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreBookingDays_Offline
        {
            get
            {
                return this.PreBookingDays_OfflineField;
            }
            set
            {
                this.PreBookingDays_OfflineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreBookingDays_Online
        {
            get
            {
                return this.PreBookingDays_OnlineField;
            }
            set
            {
                this.PreBookingDays_OnlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreTicketDays_Offline
        {
            get
            {
                return this.PreTicketDays_OfflineField;
            }
            set
            {
                this.PreTicketDays_OfflineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreTicketDays_Online
        {
            get
            {
                return this.PreTicketDays_OnlineField;
            }
            set
            {
                this.PreTicketDays_OnlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PreTicketDays_PBS
        {
            get
            {
                return this.PreTicketDays_PBSField;
            }
            set
            {
                this.PreTicketDays_PBSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceChange_MaxAmount_Online
        {
            get
            {
                return this.PriceChange_MaxAmount_OnlineField;
            }
            set
            {
                this.PriceChange_MaxAmount_OnlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Promotion
        {
            get
            {
                return this.PromotionField;
            }
            set
            {
                this.PromotionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceAppID
        {
            get
            {
                return this.SourceAppIDField;
            }
            set
            {
                this.SourceAppIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceURL
        {
            get
            {
                return this.SourceURLField;
            }
            set
            {
                this.SourceURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ticketor
        {
            get
            {
                return this.TicketorField;
            }
            set
            {
                this.TicketorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WingonRerouteFees
        {
            get
            {
                return this.WingonRerouteFeesField;
            }
            set
            {
                this.WingonRerouteFeesField = value;
            }
        }
    }
}
namespace Ticket.Entity.Rest
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityInfo", Namespace="http://schemas.datacontract.org/2004/07/Ticket.Entity.Rest", IsReference=true)]
    public partial class CityInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Ticket.Entity.Rest.AirportInfo[] AirportsField;
        
        private System.Nullable<int> CityIDField;
        
        private string CodeField;
        
        private Ticket.Entity.Rest.CountryInfo CountryField;
        
        private string EnNameField;
        
        private bool IsAliasField;
        
        private string ZhNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ticket.Entity.Rest.AirportInfo[] Airports
        {
            get
            {
                return this.AirportsField;
            }
            set
            {
                this.AirportsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CityID
        {
            get
            {
                return this.CityIDField;
            }
            set
            {
                this.CityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ticket.Entity.Rest.CountryInfo Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName
        {
            get
            {
                return this.EnNameField;
            }
            set
            {
                this.EnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAlias
        {
            get
            {
                return this.IsAliasField;
            }
            set
            {
                this.IsAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZhName
        {
            get
            {
                return this.ZhNameField;
            }
            set
            {
                this.ZhNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CountryInfo", Namespace="http://schemas.datacontract.org/2004/07/Ticket.Entity.Rest", IsReference=true)]
    public partial class CountryInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string EnNameField;
        
        private string ZhNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName
        {
            get
            {
                return this.EnNameField;
            }
            set
            {
                this.EnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZhName
        {
            get
            {
                return this.ZhNameField;
            }
            set
            {
                this.ZhNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AirportInfo", Namespace="http://schemas.datacontract.org/2004/07/Ticket.Entity.Rest", IsReference=true)]
    public partial class AirportInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Ticket.Entity.Rest.CityInfo CityField;
        
        private string CodeField;
        
        private string EnNameField;
        
        private string TerminalField;
        
        private string ZhNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ticket.Entity.Rest.CityInfo City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName
        {
            get
            {
                return this.EnNameField;
            }
            set
            {
                this.EnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Terminal
        {
            get
            {
                return this.TerminalField;
            }
            set
            {
                this.TerminalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZhName
        {
            get
            {
                return this.ZhNameField;
            }
            set
            {
                this.ZhNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AirlineInfo", Namespace="http://schemas.datacontract.org/2004/07/Ticket.Entity.Rest")]
    public partial class AirlineInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodeField;
        
        private string EnNameField;
        
        private string ZhNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnName
        {
            get
            {
                return this.EnNameField;
            }
            set
            {
                this.EnNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZhName
        {
            get
            {
                return this.ZhNameField;
            }
            set
            {
                this.ZhNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CacheInfo", Namespace="http://schemas.datacontract.org/2004/07/Ticket.Entity.Rest")]
    public partial class CacheInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime CreateTimeField;
        
        private string DescriptionField;
        
        private int ExpireMinutesField;
        
        private System.DateTime ExpireTimeField;
        
        private string KeyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpireMinutes
        {
            get
            {
                return this.ExpireMinutesField;
            }
            set
            {
                this.ExpireMinutesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpireTime
        {
            get
            {
                return this.ExpireTimeField;
            }
            set
            {
                this.ExpireTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITicketBasicService")]
public interface ITicketBasicService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketBasicService/SearchCommonConfig", ReplyAction="http://tempuri.org/ITicketBasicService/SearchCommonConfigResponse")]
    Ticket.Entity.CommonConfigCacheBO SearchCommonConfig();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketBasicService/SearchCommonConfig", ReplyAction="http://tempuri.org/ITicketBasicService/SearchCommonConfigResponse")]
    System.Threading.Tasks.Task<Ticket.Entity.CommonConfigCacheBO> SearchCommonConfigAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketBasicService/GetCityInfos", ReplyAction="http://tempuri.org/ITicketBasicService/GetCityInfosResponse")]
    Ticket.Entity.Rest.CityInfo[] GetCityInfos();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketBasicService/GetCityInfos", ReplyAction="http://tempuri.org/ITicketBasicService/GetCityInfosResponse")]
    System.Threading.Tasks.Task<Ticket.Entity.Rest.CityInfo[]> GetCityInfosAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketBasicService/GetAirlineInfos", ReplyAction="http://tempuri.org/ITicketBasicService/GetAirlineInfosResponse")]
    Ticket.Entity.Rest.AirlineInfo[] GetAirlineInfos();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketBasicService/GetAirlineInfos", ReplyAction="http://tempuri.org/ITicketBasicService/GetAirlineInfosResponse")]
    System.Threading.Tasks.Task<Ticket.Entity.Rest.AirlineInfo[]> GetAirlineInfosAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketBasicService/GetCacheInfo", ReplyAction="http://tempuri.org/ITicketBasicService/GetCacheInfoResponse")]
    Ticket.Entity.Rest.CacheInfo[] GetCacheInfo();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketBasicService/GetCacheInfo", ReplyAction="http://tempuri.org/ITicketBasicService/GetCacheInfoResponse")]
    System.Threading.Tasks.Task<Ticket.Entity.Rest.CacheInfo[]> GetCacheInfoAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketBasicService/ClearCache", ReplyAction="http://tempuri.org/ITicketBasicService/ClearCacheResponse")]
    void ClearCache(string key);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketBasicService/ClearCache", ReplyAction="http://tempuri.org/ITicketBasicService/ClearCacheResponse")]
    System.Threading.Tasks.Task ClearCacheAsync(string key);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITicketBasicServiceChannel : ITicketBasicService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TicketBasicServiceClient : System.ServiceModel.ClientBase<ITicketBasicService>, ITicketBasicService
{
    
    public TicketBasicServiceClient()
    {
    }
    
    public TicketBasicServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TicketBasicServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TicketBasicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TicketBasicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Ticket.Entity.CommonConfigCacheBO SearchCommonConfig()
    {
        return base.Channel.SearchCommonConfig();
    }
    
    public System.Threading.Tasks.Task<Ticket.Entity.CommonConfigCacheBO> SearchCommonConfigAsync()
    {
        return base.Channel.SearchCommonConfigAsync();
    }
    
    public Ticket.Entity.Rest.CityInfo[] GetCityInfos()
    {
        return base.Channel.GetCityInfos();
    }
    
    public System.Threading.Tasks.Task<Ticket.Entity.Rest.CityInfo[]> GetCityInfosAsync()
    {
        return base.Channel.GetCityInfosAsync();
    }
    
    public Ticket.Entity.Rest.AirlineInfo[] GetAirlineInfos()
    {
        return base.Channel.GetAirlineInfos();
    }
    
    public System.Threading.Tasks.Task<Ticket.Entity.Rest.AirlineInfo[]> GetAirlineInfosAsync()
    {
        return base.Channel.GetAirlineInfosAsync();
    }
    
    public Ticket.Entity.Rest.CacheInfo[] GetCacheInfo()
    {
        return base.Channel.GetCacheInfo();
    }
    
    public System.Threading.Tasks.Task<Ticket.Entity.Rest.CacheInfo[]> GetCacheInfoAsync()
    {
        return base.Channel.GetCacheInfoAsync();
    }
    
    public void ClearCache(string key)
    {
        base.Channel.ClearCache(key);
    }
    
    public System.Threading.Tasks.Task ClearCacheAsync(string key)
    {
        return base.Channel.ClearCacheAsync(key);
    }
}
